### ISSUE TITLE
Stil von M+ WeakAura / Addon

### ISSUE THREAD

**Issue by Dalerija** [mBlinkii/MaUI-ElvUI-Profile-Strings#1]
Erst einmal vielen lieben Dank für die grandiose Arbeit. Wie hast du die Weakaura so unglaublich geil hinbekommen für M+? Würdest du die veröffentlichen?

LG Dalerija

**Comment by mBlinkii** [comment]
Hallo, welche WA meinst du um genau zu sein?

**Comment by Dalerija** [comment]
![Screenshot 2022-05-16 200002](https://user-images.githubusercontent.com/105657942/168654473-4574005c-1fbf-4954-a552-a1085a8da2af.png)

**Comment by mBlinkii** [comment]
ach das ist ein Addon Warpdeplete.
