### ISSUE TITLE
Fehler beim 40 Mann Raid

### ISSUE THREAD

**Issue by Dalerija** [mBlinkii/MaUI-ElvUI-Profile-Strings#10]
Hi Blinkii,

das ist mir heute aufgefallen.
![WoWScrnShot_110422_213455](https://user-images.githubusercontent.com/105657942/200069432-25d50866-354d-4411-8ea7-d9bca756d111.jpg)

**Comment by mBlinkii** [comment]
![image](https://user-images.githubusercontent.com/92640275/200126872-11aaa42a-141b-4512-ac17-44167072aff3.png)

Hi, danke dir, so kannst du das Problem beheben. einfach den Text Löschen.
