### ISSUE TITLE
mMediaTag defekt

### ISSUE THREAD

**Issue by Dalerija** [mBlinkii/MaUI-ElvUI-Profile-Strings#11]
Hi,

du wirst es ja schon selber sehen aber die mMediaTag läuft nicht mehr sauber. Leider hab ich das alleine nicht fixen können. :)

**Comment by mBlinkii** [comment]
Huhu, Sorry für die späte Antwort, ja mit der neuesten Version von mMediaTag sollte auch schon wieder alles laufen. Danke dir für das fleißige melden von Fehler die dir auffallen. Grüße Blinkii
