### ISSUE TITLE
Schriftfarbe

### ISSUE THREAD

**Issue by Dalerija** [mBlinkii/MaUI-ElvUI-Profile-Strings#14]
Hallo mein Lieber,

mal wieder grandiose Leistung. Vielen lieben Dank. Bisher keine Fehler gefunden. Kannst du mir sagen, wie ich beim Charakter Fenster die Schriftfarbe auf normal setzen kann. Das Lila vom DH ist unangenehm zu lesen. Kannst du mir auch noch sagen wo ich einstellen kann, wo der Text für die aufgenommenen Sachen verschieben kann? Und irgendwie ist mein Talentfenster skaliert. Kann man die Grösse da auch anpassen? 

Oder kann ich Eltruism weg lassen? Dient das nur zur Kosmetik oder sind da relevante Sachen eingestellt?

Fragen über Fragen :)

Danke dir.

**Comment by mBlinkii** [comment]
Hallo Dalerija, Eltruism ist komplett optional aber und nur für den Farbverlauf der Klassen Farben verantwortlich. 

Das Interface wird ohne die Optionalen Addons gut aussehen und Funktioniert. Ich versuche immer so wenig Abhängigkeit zu haben wie möglich. Deshalb ist diesmal auch nur ElvUi und mMediaTag erforderlich. 

Die Farben kannst du in Eltruism unter Farbverlauf einstellen. Wenn du den Farbverlauf komplett deaktivieren willst dann, deaktiviere einfach Eltruism. 

In mMediaTag habe ich auch noch ein Modul zum anpassen der Klassenfarben, das wird aktive wenn Eltruism nicht aktive ist. Die Farbe kannst du dann unter Kosmetisch > Benutzerdefinierte Klassenfarben änder deaktivieren. 

Das mit der Skalierung des Talentfensters ist auch von Eltruism, ich hatte es mal getestet und vergessen vor dem Export wieder raus zu nehmen. 

Ich werde die Tage ein Update raus bringen, zusammen mit mMediaTag. Ich habe noch ein paar Sachen angepasst und Optimiert. 

Danke für deine Rückmeldung. 

Grüße 
Blinkii

**Comment by Dalerija** [comment]
Vielen lieben Dank für die schnelle Antwort. Habe es heute Morgen auch mal raus genommen. Wenn man dir helfen kann mit testen etc. einfach Bescheid geben.
