### ISSUE TITLE
ElveUI Update Error

### ISSUE THREAD

**Issue by Dalerija** [mBlinkii/MaUI-ElvUI-Profile-Strings#15]
Hallo mein Lieber,

hab soeben ElveUI aktualisisert etc. Anscheinend ist da nun was anders. Nur als Info.

![WoWScrnShot_020823_191400](https://user-images.githubusercontent.com/105657942/217616818-842ac55e-d110-4e65-adb3-1a241bcf5529.jpg)

Leisten fehlen auf einmal :)

**Comment by mBlinkii** [comment]
Hallo, ja das ist ein Bug in ElvUi, wenn du die Aktuelle dev Version von ElvUi dir von Github lädst, dann sollte der Fehler behoben sein. LG

**Comment by Dalerija** [comment]
Hallo,

danke dir das wars.

**Comment by mBlinkii** [comment]
Habe die Profile heute auch aktualisiert.
