### ISSUE TITLE
Pfeile zum Togglen von Chatfenstern & Details Embed verschwinden 

### ISSUE THREAD

**Issue by handy4** [mBlinkii/MaUI-ElvUI-Profile-Strings#17]
Hallihallo,
Erstmal: Danke für dieses wahnsinnig gute UI-Profil. Was die out-of-the-box-Leistung angeht bin ich wirklich super zufrieden. Ich habe hier und da für mich ein Paar Kleinigkeiten angepasst, aber grundsätzlich bin ich super happy.

Eine Anpassung die ich gerne noch machen würde, aber einfach nicht hinbekomme ist folgende. Normalerweise gibt es ja unter den Chatfenstern so Pfeile, mit denen man diese aus- und einblenden kann. Vor allem lässt sich mit einem Rechtsklick der Embed von AddOnSkins aus- und einblenden. Ich wäre gern in der Lage nach Bedarf die Chatfenster zu togglen und Details anzuzeigen. Leider scheinen diese Pfeile standardmäßig ausgeblendet zu sein und die Einstellungen "Hide Chat Toggles" und "Fade Chat Toggles" in den ElvUI Chat Panels Settings tun auch nichts. Teilweise hab ich es beim Rumspielen an Einstellungen kurzzeitig geschafft die Pfeile wieder zu bekommen, aber spätestens beim nächsten UI Reload sind sie wieder weg.

Hast du eine Idee, wie ich besagte Pfeile zurück bekommen könnte oder ihre Funktion replizieren kann?
Danke!

**Comment by mBlinkii** [comment]
Hallo du musst die Chatleisten und den Schalter aktivieren. Dazu gehts du am besten wie folgt vor 

```
1. ElvUI > Infotexte > Leisten > Infotextleiste (links) > Eingeschaltet - anklicken
2. ElvUI > Infotexte > Leisten > Infotextleiste (rechts) > Eingeschaltet - anklicken
3. ElvUI > Chat > Leisten > Verstecke Chatschalter - muss nicht angeklickt sein
```

damit sollte es dann funktionieren.
