### ISSUE TITLE
Richtige Beschreibung in den Nameplates

### ISSUE THREAD

**Issue by Dalerija** [mBlinkii/MaUI-ElvUI-Profile-Strings#18]
Blinkii du alter Haudegen. Wie konnte man den Fehler in den Nameplates noch mal beheben. Ich finde es gerade nicht mehr. Oder bist du sowieso gerade an einem 10.1 Update dran, dann warte ich noch. 

![WoWScrnShot_050523_143238](https://user-images.githubusercontent.com/105657942/236458698-46a578e4-3028-41ef-b8fe-299b4d40a316.jpg)

**Comment by mBlinkii** [comment]
Hallo Dalerija, ich habe soeben die profile für Tank/DD, Global und Privat aktualisiert.

**Comment by Vasxy** [comment]
Hallo, beim healer center & left ist momentan dasselbe Problem.

**Comment by mBlinkii** [comment]
Hallo, Ich habe die Heiler Profile noch nicht aktualisiert, du müsstest für jede Einheit und für die Namensplaketten die TAGs ändern. Vielleicht schaffe ich es heute ein Update für die Profile zu erstellen.
