### ISSUE TITLE
Richtige Beschreibung in den Nameplates

### ISSUE THREAD

**Issue by Vasxy** [mBlinkii/MaUI-ElvUI-Profile-Strings#19]
Wie kann man den Fehler in den Nameplates beheben. Ich finde es gerade nicht mehr.

Tritt bei Healer Center & left auf. 

lg

![IMG_3291](https://github.com/mBlinkii/MaUI-ElvUI-Profile-Strings/assets/135066933/d08dc1ce-0026-4f92-9666-9908c199e1da)

**Comment by mBlinkii** [comment]
Hallo, Ich habe die Heiler Profile noch nicht aktualisiert, du müsstest für jede Einheit und für die Namensplaketten die TAGs ändern. Vielleicht schaffe ich es heute ein Update für die Profile zu erstellen.

**Comment by mBlinkii** [comment]
Als Beispiel: so gehst du vor ElvUi > Einheitfenster > Individuelle > Spieler > Benutzerdefinierte Texte und dort änderst du mHealth:Short:Icon in mHealth:icon:short. Alle verfügbaren TAGs sind unter ElvUi > Verfügbare Tags einzusehen.

**Comment by xoDragonsbadxo** [comment]
I'm so glad this was here. I was getting ready to reset all my folders, thinking I did something wrong cus my unit frames were doing the same thing. :)

**Comment by mBlinkii** [comment]
See here https://github.com/mBlinkii/MaUI-ElvUI-Profile-Strings/issues/20
