### ISSUE TITLE
Anzeige

### ISSUE THREAD

**Issue by Dalerija** [mBlinkii/MaUI-ElvUI-Profile-Strings#21]
Hey Ho, 
es gab wohl mal wieder ein Update. Wegen der Anzeige beim Boss.
Lg 
![WoWScrnShot_101523_162203](https://github.com/mBlinkii/MaUI-ElvUI-Profile-Strings/assets/105657942/b95d209e-9750-4169-b13c-f50409f644c1)

**Comment by mBlinkii** [comment]
Hallo, ja ich habe den Tag überarbeitet, du müsstest den einmal selbst unter ElvUI > Namensplaketten > Gegnerische NPC > Titel zu [mColor:target][mTarget:abbrev:veryshort] ändern.
