### ISSUE TITLE
Welches ist Tank/DD Profile

### ISSUE THREAD

**Issue by Dalerija** [mBlinkii/MaUI-ElvUI-Profile-Strings#3]
Hi Blinkii,

aktuell steht in der Übersicht Classic HEal und noch mal Heal. Welches wäre deine DD /Tank Version?

Lg und Danke

**Comment by mBlinkii** [comment]
Huhu,

für Retail sind die Profile hier zu finden https://github.com/mBlinkii/MaUI-v5-ElvUI-Profile-Strings/tree/main/MaUI%20v5%20Strings

und für Classic hier https://github.com/mBlinkii/MaUI-v5-ElvUI-Profile-Strings/tree/main/MaUI%20v5%20Classic%20Strings

für Classic gibt es noch keine Heiler Profil.

Grüße
