### ISSUE TITLE
DD/Tank und Heal Profile zu ähnlich

### ISSUE THREAD

**Issue by dnlxh** [mBlinkii/MaUI-ElvUI-Profile-Strings#4]
Hey,

ist es gewollt, dass das Healer Layout mittlerweile einfach nur aussieht wie das DD/Tank Layout, mit dem Einzige Unterschied, dass die Gruppen etwas mittiger Positioniert sind und nicht ganz am Rand? Wenn ja, schade. So muss man sich das ganze ja dann doch wieder zurecht pflücken :D Das alte Healer UI war um einiges Angenehmer zu spielen direkt nach dem Import.

Die Group frames so weit außen zu haben ist für mich zumindest gewöhnungsbedürftig, da mein Blick dann so weit rüber wandert, dass ich von  dem was in der Mitte passiert nicht viel mitbekomme.

Oder kommt mit der Zeit evtl noch ein "richtiges" Healer Layout?

**Comment by mBlinkii** [comment]
Hallo dlnxh, da ich aktuell kein Heiler spiele ist es für mich um so schwere es anderen recht zu machen. Aber wenn du sagst die hat das alte Layout besser gefallen, dann werde ich das neue anpassen. 

Danke für dein Feedback

**Comment by dnlxh** [comment]
Hey,

ich meine, man kann dein jetziges Layout ja gut und schnell zurecht schieben. Aber im vergleich zu früher halt ein downgrade. Dein Interface war bisher nämlich immer out of the box super benutzbar.  :) Bin gespannt was du so bastelst!
