### ISSUE TITLE
Fehler beim Entschlüsseln der Daten. Die importierende Zeichenfolge scheint beschädigt zu sein!

### ISSUE THREAD

**Issue by marciiiGH** [mBlinkii/MaUI-ElvUI-Profile-Strings#5]
Moin, 

ich wollte dein Profil für TBC Classic nutzen, bekomme beim Importieren deiner Strings aber besagte Fehlermeldung von ElvUi angezeigt. Irgendeine Idee woran das liegen könnte?

MfG
![Screenshot_6](https://user-images.githubusercontent.com/110308151/181994717-f91b3697-cd40-4ae0-9dff-a5293c8b78d7.jpg)

**Comment by mBlinkii** [comment]
Hallo, achte bitte darauf das sich am ende kein Leerzeichen mit eingeschlichen hat. 

LG
Blinkii

**Comment by marciiiGH** [comment]
´Lag tatsächlich am Leerzeichen, vielen Dank, Problem behoben. :D

**Comment by mBlinkii** [comment]
Super =)
