### ISSUE TITLE
Hilfe bei der Arbeit.

### ISSUE THREAD

**Issue by Dalerija** [mBlinkii/MaUI-ElvUI-Profile-Strings#7]
Hey Blinkii. Kann man dich mit deinem UI eigentlich irgendwie unterstützen? oder helfen? LG Bene

**Comment by mBlinkii** [comment]
Hallo und sorry für die späte Antwort. Ich hatte nicht viel Zeit zum Spielen und updaten des Interfaces. Im Moment sollte alles wieder funktionieren. Unterstützung beim Addon Testen/ Fehler melden wäre sehr nett. Grüße Blinkii

**Comment by Dalerija** [comment]
Vielen Dank. Ich helfe dir gerne. Du kannst mich sonst auch so kontaktieren wenn es Sachen zum testen gäbe. Dalerion#21369 oder Discord Dalerija/Bene#4063
