### ISSUE TITLE
Eventuell einen Tip

### ISSUE THREAD

**Issue by Dalerija** [mBlinkii/MaUI-ElvUI-Profile-Strings#9]
Soweit sieht nach deinem Media Addon Update nun fast alles gut aus. Aber es bombadiert einen noch mit Fehlern. Du bist ein wenig mehr in der Materie und der ElveUI Discord war leider nicht so erfolgreich. Addons und ElveUI etc. sind alle aktuell. Hast du die Fehler bei dir auch?

`10x ...Ons/ProjectAzilroka/Modules/SquareMinimapButtons.lua:194: attempt to index field 'MiniMapMailFrame' (a nil value)
[string "@Interface/AddOns/ProjectAzilroka/Modules/SquareMinimapButtons.lua"]:194: in function `?'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...vUI/Libraries/Core/Ace/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:363
 EnableModule = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceTimer-3.0/AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHookScript = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceHook-3.0/AceHook-3.0.lua:409
 RawHookScript = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceHook-3.0/AceHook-3.0.lua:394
 PartialIgnore = <table> {
 }
 OnDragStop = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/SquareMinimapButtons.lua:186
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:405
 defaultModuleState = true
 IsEnabled = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:447
 ScheduleTimer = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceTimer-3.0/AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:346
 Authors = "Azilroka    Sinaris    Omega    Durc"
 RegisterMessage = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 Update = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/SquareMinimapButtons.lua:538
 IsHooked = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceHook-3.0/AceHook-3.0.lua:492
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 RegisterEvent = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 OverrideTexture = <table> {
 }
 IterateModules = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:433
 Title = "|cFF16C3F2Square|r |cFFFFFFFFMinimap Buttons|r"
 RawHook = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceHook-3.0/AceHook-3.0.lua:312
 isEnabled = true
 DoNotCrop = <table> {
 }
 Bar = SquareMinimapButtonBar {
 }
 UnlockButton = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/SquareMinimapButtons.lua:146
 Enable = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:290
 UnregisterAllEvents = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 GetModule = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:206
 defaultModuleLibraries = <table> {
 }
 OnUpdate = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/SquareMinimapButtons.lua:160
 HandleBlizzardButtons = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/SquareMinimapButtons.lua:190
 ScheduleRepeatingTimer = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceTimer-3.0/AceTimer-3.0.lua:129
 Buttons = <table> {
 }
 GetName = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:275
 GetOptions = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/SquareMinimapButtons.lua:614
 GenericIgnore = <table> {
 }
 name = "ProjectAzilroka_SquareMinimapButtons"
 Initialize = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/SquareMinimapButtons.lua:683
 orderedModules = <table> {
 }
 Disable = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:310
 Description = "Minimap Button Bar / Minimap Button Skinning"
 Hider = Frame`

**Comment by mBlinkii** [comment]
Das scheint alles von ProjectAzilroka https://github.com/Azilroka/ProjectAzilroka/tree/main/ProjectAzilroka, ich denke er hat auch noch kein Update bereit gestellt. Ich habe zurzeit auch nur ElvUi, AddonSkins und mMediaTag aktive.

**Comment by mBlinkii** [comment]
Danke für die info

**Comment by Dalerija** [comment]
Er oder sie hat heute Nacht eine neue Alpha veröffentlicht. Wenn du die nimmst sind die Bugs weg :)
